name: Build and Publish

on:
  push:
    tags:
      - 'dev-*'
      - 'stag-*'
      - 'prod-*'

jobs:
  build-development:
    if: startsWith(github.ref, 'refs/tags/dev-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd web-app
          npm install

      - name: Build Vue.js app for Development
        run: |
          npm run build:development
        working-directory: ./web-app

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Publish .NET application for Development
        run: |
          export ASPNETCORE_ENVIRONMENT=Development
          rm -rf publish
          dotnet publish -c Release -o ./publish

      - name: Zip the publish folder
        run: |
          zip -r publish-dev.zip ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish-zip-development
          path: publish-dev.zip

  build-staging:
    if: startsWith(github.ref, 'refs/tags/stag-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd web-app
          npm install

      - name: Build Vue.js app for Staging
        run: |
          npm run build:staging
        working-directory: ./web-app

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Publish .NET application for Staging
        run: |
          export ASPNETCORE_ENVIRONMENT=Staging
          rm -rf publish
          dotnet publish -c Release -o ./publish

      - name: Zip the publish folder
        run: |
          zip -r publish-stag.zip ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish-zip-staging
          path: publish-stag.zip

  build-production:
    if: startsWith(github.ref, 'refs/tags/prod-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd web-app
          npm install

      - name: Build Vue.js app for Production
        run: |
          npm run build:production
        working-directory: ./web-app

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Publish .NET application for Production
        run: |
          export ASPNETCORE_ENVIRONMENT=Production
          rm -rf publish
          dotnet publish -c Release -o ./publish

      - name: Zip the publish folder
        run: |
          zip -r publish-prod.zip ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish-zip-production
          path: publish-prod.zip
